import React, { useState } from 'react';
import {
  Sparkles,
  Zap,
  ChevronDown,
  ChevronUp,
  FileText,
  Send,
  CheckCircle2,
} from 'lucide-react';
import type { TopicRecommendation } from '../types/analytics';
import { MOCK_TOPICS } from '../services/mockData';

export const AITopicFeed: React.FC = () => {
  const [topics, setTopics] = useState<TopicRecommendation[]>(MOCK_TOPICS);
  const [expandedTopicId, setExpandedTopicId] = useState<string | null>(topics[0]?.id || null);
  const [customPrompt, setCustomPrompt] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState<boolean>(false);

  const handleGenerateCustomTopic = (e: React.FormEvent) => {
    e.preventDefault();
    if (!customPrompt.trim()) return;

    setIsGenerating(true);
    setTimeout(() => {
      const newTopic: TopicRecommendation = {
        id: `topic_custom_${Date.now()}`,
        title: `AI Predictive Concept: ${customPrompt}`,
        angle: 'Custom Prompt Strategy',
        hookScript: `Hook: In the next 60 seconds, we break down "${customPrompt}" and why it matters for your channel.`,
        category: 'Tutorial',
        expectedScore: Math.floor(Math.random() * 10) + 90,
        potentialReach: 'Viral Potential',
        targetAudienceDemographic: '18-34 Tech Enthusiasts & Developers in India & US',
        dataTrigger: `Custom AI simulation based on your channel's 1:30 drop-off & retention benchmarks for topic: "${customPrompt}".`,
        suggestedDuration: '10-12 mins',
        targetPlatform: 'youtube_long',
        outline: [
          `0:00-0:30 -> Hook addressing "${customPrompt}" core frustration`,
          '0:30-3:00 -> Quick architecture diagram showing common pitfalls',
          '3:00-7:00 -> Step-by-step implementation demo',
          '7:00-10:00 -> Performance benchmarking & key takeaways'
        ]
      };

      setTopics([newTopic, ...topics]);
      setExpandedTopicId(newTopic.id);
      setCustomPrompt('');
      setIsGenerating(false);
    }, 1200);
  };

  return (
    <div className="space-y-6">
      <div className="glass-panel p-6 rounded-2xl border border-creator-border flex flex-col lg:flex-row lg:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="p-2 rounded-lg bg-ai-cyan/10 text-ai-cyan">
              <Sparkles className="w-5 h-5 animate-pulse" />
            </span>
            <h2 className="text-xl font-bold text-white tracking-tight">AI Topic Recommendation Engine</h2>
          </div>
          <p className="text-sm text-creator-muted mt-1">
            Predictive video ideas generated by combining viewer drop-off analytics, high-retention timestamps, and audience demand.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <div className="bg-creator-card px-3.5 py-2 rounded-xl border border-creator-border text-xs text-slate-300">
            Engine Model: <span className="font-bold text-ai-cyan">Antigravity Predictive LLM v2</span>
          </div>
        </div>
      </div>

      <form onSubmit={handleGenerateCustomTopic} className="glass-panel p-4 rounded-2xl border border-creator-border flex items-center gap-3">
        <div className="p-2 rounded-xl bg-ai-indigo/10 text-ai-indigo">
          <Zap className="w-5 h-5" />
        </div>
        <input
          type="text"
          value={customPrompt}
          onChange={(e) => setCustomPrompt(e.target.value)}
          placeholder="Ask AI to analyze a custom video concept (e.g. 'Next.js 15 Server Actions setup')..."
          className="flex-1 bg-transparent text-white text-sm placeholder-creator-muted focus:outline-none"
        />
        <button
          type="submit"
          disabled={isGenerating || !customPrompt.trim()}
          className="px-5 py-2.5 bg-gradient-to-r from-ai-cyan to-ai-indigo hover:from-cyan-400 hover:to-indigo-500 text-white font-bold text-xs rounded-xl transition shadow-glow-cyan flex items-center gap-2 disabled:opacity-50"
        >
          {isGenerating ? (
            <>
              <Sparkles className="w-4 h-4 animate-spin" />
              Analyzing Channel Retention...
            </>
          ) : (
            <>
              <Send className="w-4 h-4" />
              Predict Score
            </>
          )}
        </button>
      </form>

      <div className="space-y-4">
        {topics.map((topic) => {
          const isExpanded = expandedTopicId === topic.id;

          return (
            <div
              key={topic.id}
              className={`glass-panel rounded-2xl border transition-all ${
                isExpanded ? 'border-ai-cyan shadow-glow-cyan bg-creator-card/90' : 'border-creator-border hover:border-slate-600'
              }`}
            >
              <div
                onClick={() => setExpandedTopicId(isExpanded ? null : topic.id)}
                className="p-5 flex flex-col md:flex-row md:items-center justify-between gap-4 cursor-pointer"
              >
                <div className="space-y-1.5 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="px-2.5 py-0.5 rounded-full text-[11px] font-extrabold bg-ai-cyan/20 text-ai-cyan border border-ai-cyan/40">
                      Score: {topic.expectedScore}/100
                    </span>
                    <span className="px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-slate-800 text-slate-300">
                      {topic.category}
                    </span>
                    <span className="px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-emerald-500/20 text-emerald-400">
                      {topic.potentialReach}
                    </span>
                  </div>

                  <h3 className="text-lg font-bold text-white tracking-tight">{topic.title}</h3>
                  <p className="text-xs text-creator-muted flex items-center gap-1.5">
                    <span className="font-semibold text-slate-300">Angle:</span> {topic.angle}
                  </p>
                </div>

                <div className="flex items-center gap-3">
                  <div className="text-right text-xs">
                    <div className="text-creator-muted">Target Duration</div>
                    <div className="font-bold text-white">{topic.suggestedDuration}</div>
                  </div>

                  <button className="p-2 rounded-xl bg-creator-card border border-creator-border text-creator-muted hover:text-white">
                    {isExpanded ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
                  </button>
                </div>
              </div>

              {isExpanded && (
                <div className="px-5 pb-5 pt-2 border-t border-creator-border space-y-4">
                  <div className="p-3.5 bg-ai-indigo/10 border border-ai-indigo/30 rounded-xl text-xs text-indigo-200">
                    <strong className="text-ai-cyan">Data Trigger Justification:</strong> {topic.dataTrigger}
                  </div>

                  <div>
                    <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-2 flex items-center gap-1.5">
                      <FileText className="w-4 h-4 text-ai-cyan" />
                      Suggested Video Structure Outline
                    </h4>
                    <div className="space-y-1.5 bg-creator-card p-4 rounded-xl border border-creator-border">
                      {topic.outline.map((step, idx) => (
                        <div key={idx} className="flex items-start gap-2.5 text-xs text-slate-300">
                          <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                          <span>{step}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};
